bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

client:
  brawlStars:
    url: ${BRAWL_STARS_URL:https://api.brawlstars.com/v1/}
    apiKey: ${BRAWL_STARS_API_KEY}

spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/brawl_stars_monitoring_bot_db}
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
